//! Editor action identifiers used by key bindings.
//!
//! These names are stable user-facing strings shared with import reports and the
//! future command palette. Unknown names are errors so imports can explain loss.

use std::{fmt, str::FromStr};

/// A command that can be reached through the keymap or command palette.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum EditorAction {
    CursorUp,
    CursorDown,
    CursorLeft,
    CursorRight,
    CursorWordLeft,
    CursorWordRight,
    CursorLineStart,
    CursorLineEnd,
    CursorBufferStart,
    CursorBufferEnd,
    CursorPageUp,
    CursorPageDown,
    SelectionUp,
    SelectionDown,
    SelectionLeft,
    SelectionRight,
    SelectionWordLeft,
    SelectionWordRight,
    SelectionLineStart,
    SelectionLineEnd,
    SelectionBufferStart,
    SelectionBufferEnd,
    SelectionPageUp,
    SelectionPageDown,
    SelectionAll,
    EditBackspace,
    EditDelete,
    EditDeleteWordLeft,
    EditDeleteToLineStart,
    EditInsertLineAfter,
    EditInsertLineBefore,
    EditMoveLinesUp,
    EditMoveLinesDown,
    EditUndo,
    EditRedo,
    SearchOpen,
    SearchNext,
    SearchPrevious,
    ReplaceOpen,
    ReplaceNext,
    ReplaceAll,
    BufferNew,
    BufferNext,
    BufferPrevious,
    BufferClose,
    FileSave,
    FileSaveAs,
    ViewSplitVertical,
    ViewFocusNextSplit,
    ViewFocusPreviousSplit,
    PaletteOpen,
    AppQuit,
    InspectorOpen,
}

impl EditorAction {
    /// Stable list of commands exposed through the command palette.
    pub const ALL: &[Self] = &[
        Self::CursorUp,
        Self::CursorDown,
        Self::CursorLeft,
        Self::CursorRight,
        Self::CursorWordLeft,
        Self::CursorWordRight,
        Self::CursorLineStart,
        Self::CursorLineEnd,
        Self::CursorBufferStart,
        Self::CursorBufferEnd,
        Self::CursorPageUp,
        Self::CursorPageDown,
        Self::SelectionUp,
        Self::SelectionDown,
        Self::SelectionLeft,
        Self::SelectionRight,
        Self::SelectionWordLeft,
        Self::SelectionWordRight,
        Self::SelectionLineStart,
        Self::SelectionLineEnd,
        Self::SelectionBufferStart,
        Self::SelectionBufferEnd,
        Self::SelectionPageUp,
        Self::SelectionPageDown,
        Self::SelectionAll,
        Self::EditBackspace,
        Self::EditDelete,
        Self::EditDeleteWordLeft,
        Self::EditDeleteToLineStart,
        Self::EditInsertLineAfter,
        Self::EditInsertLineBefore,
        Self::EditMoveLinesUp,
        Self::EditMoveLinesDown,
        Self::EditUndo,
        Self::EditRedo,
        Self::SearchOpen,
        Self::SearchNext,
        Self::SearchPrevious,
        Self::ReplaceOpen,
        Self::ReplaceNext,
        Self::ReplaceAll,
        Self::BufferNew,
        Self::BufferNext,
        Self::BufferPrevious,
        Self::BufferClose,
        Self::FileSave,
        Self::FileSaveAs,
        Self::ViewSplitVertical,
        Self::ViewFocusNextSplit,
        Self::ViewFocusPreviousSplit,
        Self::PaletteOpen,
        Self::AppQuit,
        Self::InspectorOpen,
    ];

    /// Canonical action name used in bindings and import reports.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::CursorUp => "cursor.up",
            Self::CursorDown => "cursor.down",
            Self::CursorLeft => "cursor.left",
            Self::CursorRight => "cursor.right",
            Self::CursorWordLeft => "cursor.wordLeft",
            Self::CursorWordRight => "cursor.wordRight",
            Self::CursorLineStart => "cursor.lineStart",
            Self::CursorLineEnd => "cursor.lineEnd",
            Self::CursorBufferStart => "cursor.bufferStart",
            Self::CursorBufferEnd => "cursor.bufferEnd",
            Self::CursorPageUp => "cursor.pageUp",
            Self::CursorPageDown => "cursor.pageDown",
            Self::SelectionUp => "selection.up",
            Self::SelectionDown => "selection.down",
            Self::SelectionLeft => "selection.left",
            Self::SelectionRight => "selection.right",
            Self::SelectionWordLeft => "selection.wordLeft",
            Self::SelectionWordRight => "selection.wordRight",
            Self::SelectionLineStart => "selection.lineStart",
            Self::SelectionLineEnd => "selection.lineEnd",
            Self::SelectionBufferStart => "selection.bufferStart",
            Self::SelectionBufferEnd => "selection.bufferEnd",
            Self::SelectionPageUp => "selection.pageUp",
            Self::SelectionPageDown => "selection.pageDown",
            Self::SelectionAll => "selection.all",
            Self::EditBackspace => "edit.backspace",
            Self::EditDelete => "edit.delete",
            Self::EditDeleteWordLeft => "edit.deleteWordLeft",
            Self::EditDeleteToLineStart => "edit.deleteToLineStart",
            Self::EditInsertLineAfter => "edit.insertLineAfter",
            Self::EditInsertLineBefore => "edit.insertLineBefore",
            Self::EditMoveLinesUp => "edit.moveLinesUp",
            Self::EditMoveLinesDown => "edit.moveLinesDown",
            Self::EditUndo => "edit.undo",
            Self::EditRedo => "edit.redo",
            Self::SearchOpen => "search.open",
            Self::SearchNext => "search.next",
            Self::SearchPrevious => "search.previous",
            Self::ReplaceOpen => "replace.open",
            Self::ReplaceNext => "replace.next",
            Self::ReplaceAll => "replace.all",
            Self::BufferNew => "buffer.new",
            Self::BufferNext => "buffer.next",
            Self::BufferPrevious => "buffer.previous",
            Self::BufferClose => "buffer.close",
            Self::FileSave => "file.save",
            Self::FileSaveAs => "file.saveAs",
            Self::ViewSplitVertical => "view.splitVertical",
            Self::ViewFocusNextSplit => "view.focusNextSplit",
            Self::ViewFocusPreviousSplit => "view.focusPreviousSplit",
            Self::PaletteOpen => "palette.open",
            Self::AppQuit => "app.quit",
            Self::InspectorOpen => "inspector.open",
        }
    }
}

/// Error returned when a binding references an unknown action name.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct ParseActionError(pub String);

impl fmt::Display for ParseActionError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "unknown editor action: {}", self.0)
    }
}

impl std::error::Error for ParseActionError {}

impl FromStr for EditorAction {
    type Err = ParseActionError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "cursor.up" => Ok(Self::CursorUp),
            "cursor.down" => Ok(Self::CursorDown),
            "cursor.left" => Ok(Self::CursorLeft),
            "cursor.right" => Ok(Self::CursorRight),
            "cursor.wordLeft" => Ok(Self::CursorWordLeft),
            "cursor.wordRight" => Ok(Self::CursorWordRight),
            "cursor.lineStart" => Ok(Self::CursorLineStart),
            "cursor.lineEnd" => Ok(Self::CursorLineEnd),
            "cursor.bufferStart" => Ok(Self::CursorBufferStart),
            "cursor.bufferEnd" => Ok(Self::CursorBufferEnd),
            "cursor.pageUp" => Ok(Self::CursorPageUp),
            "cursor.pageDown" => Ok(Self::CursorPageDown),
            "selection.up" => Ok(Self::SelectionUp),
            "selection.down" => Ok(Self::SelectionDown),
            "selection.left" => Ok(Self::SelectionLeft),
            "selection.right" => Ok(Self::SelectionRight),
            "selection.wordLeft" => Ok(Self::SelectionWordLeft),
            "selection.wordRight" => Ok(Self::SelectionWordRight),
            "selection.lineStart" => Ok(Self::SelectionLineStart),
            "selection.lineEnd" => Ok(Self::SelectionLineEnd),
            "selection.bufferStart" => Ok(Self::SelectionBufferStart),
            "selection.bufferEnd" => Ok(Self::SelectionBufferEnd),
            "selection.pageUp" => Ok(Self::SelectionPageUp),
            "selection.pageDown" => Ok(Self::SelectionPageDown),
            "selection.all" => Ok(Self::SelectionAll),
            "edit.backspace" => Ok(Self::EditBackspace),
            "edit.delete" => Ok(Self::EditDelete),
            "edit.deleteWordLeft" => Ok(Self::EditDeleteWordLeft),
            "edit.deleteToLineStart" => Ok(Self::EditDeleteToLineStart),
            "edit.insertLineAfter" => Ok(Self::EditInsertLineAfter),
            "edit.insertLineBefore" => Ok(Self::EditInsertLineBefore),
            "edit.moveLinesUp" => Ok(Self::EditMoveLinesUp),
            "edit.moveLinesDown" => Ok(Self::EditMoveLinesDown),
            "edit.undo" => Ok(Self::EditUndo),
            "edit.redo" => Ok(Self::EditRedo),
            "search.open" => Ok(Self::SearchOpen),
            "search.next" => Ok(Self::SearchNext),
            "search.previous" => Ok(Self::SearchPrevious),
            "replace.open" => Ok(Self::ReplaceOpen),
            "replace.next" => Ok(Self::ReplaceNext),
            "replace.all" => Ok(Self::ReplaceAll),
            "buffer.new" => Ok(Self::BufferNew),
            "buffer.next" => Ok(Self::BufferNext),
            "buffer.previous" => Ok(Self::BufferPrevious),
            "buffer.close" => Ok(Self::BufferClose),
            "file.save" => Ok(Self::FileSave),
            "file.saveAs" => Ok(Self::FileSaveAs),
            "view.splitVertical" => Ok(Self::ViewSplitVertical),
            "view.focusNextSplit" => Ok(Self::ViewFocusNextSplit),
            "view.focusPreviousSplit" => Ok(Self::ViewFocusPreviousSplit),
            "palette.open" => Ok(Self::PaletteOpen),
            "app.quit" => Ok(Self::AppQuit),
            "inspector.open" => Ok(Self::InspectorOpen),
            _ => Err(ParseActionError(value.to_string())),
        }
    }
}

impl fmt::Display for EditorAction {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}
