// THIRD-PARTY-NOTICES.md の generator。出荷する target の依存 crate を `cargo tree` で集め、
// local cargo registry に展開済みの LICENSE テキストを束ねて 1 ファイルにする。
// 外部ツール (cargo-about 等) を持ち込まず xtask に寄せる方針は
// docs/TASK-260828-license-and-third-party-notices.md 参照。
use crate::process::{RunOptions, run};
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

pub const NOTICES_PATH: &str = "THIRD-PARTY-NOTICES.md";

// .goreleaser.yaml の builds targets と対応させる (zig の glibc suffix は cargo tree には不要)
const SHIPPED_TARGETS: &[&str] = &[
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
];

// 同梱アセット (Rust 依存以外) の notice。生成物へそのまま転記する
const BUNDLED_ASSET_NOTICES: &[&str] = &[
    "src/highlight/assets/LICENSE-sublimehq-packages.txt",
    "src/highlight/assets/LICENSE-typescript-sublime-plugin.txt",
    "src/highlight/assets/LICENSE-sublime-toml-highlighting.txt",
    "src/highlight/assets/LICENSE-ini-syntax.txt",
    "src/highlight/assets/LICENSE-docker-tmbundle.txt",
];

// crate が本文を publish していない場合の救済用 canonical text。Apache-2.0 は §4(a) が
// 受領者へのライセンスコピーの提供を要求するため、リンクでは代替できない
const APACHE_2_0_TEXT: &str = include_str!("../assets/LICENSE-Apache-2.0.txt");

pub fn generate() -> Result<(), String> {
    let crates = shipped_dependencies()?;
    let registry_dirs = registry_src_dirs()?;

    let mut output = String::from(
        "# Third Party Notices\n\n\
         coda binary distributions bundle the third party software listed below.\n\
         This file is generated by `cargo xtask licenses` — do not edit by hand.\n",
    );

    for (name, version) in &crates {
        output.push_str(&format!("\n## {name} {version}\n\n"));
        let dir = find_crate_dir(&registry_dirs, name, version).ok_or_else(|| {
            format!(
                "{name} {version} is not extracted in the local cargo registry; \
                 build coda for all shipped targets once, then retry"
            )
        })?;
        let expression = license_expression(&dir);
        if let Some(expression) = &expression {
            output.push_str(&format!("License: {expression}\n\n"));
        }
        // `A AND B` 型の複合ライセンスで必須本文を落とさないよう、選抜せず全ファイルを収録する
        let texts = license_texts(&dir)?;
        if texts.is_empty() {
            // 完全一致に限定する。複合式 (Apache-2.0 AND X 等) を Apache 本文だけで
            // 通してしまうと X の必須本文が欠落するため
            let is_apache = expression.as_deref() == Some("Apache-2.0");
            if !is_apache {
                return Err(format!(
                    "no license text found for {name} {version}; add a canonical fallback to xtask/src/licenses.rs"
                ));
            }
            output.push_str(
                "This crate does not bundle its license text. \
                 The standard Apache License 2.0 text follows.\n\n```text\n",
            );
            output.push_str(APACHE_2_0_TEXT.trim_end());
            output.push_str("\n```\n");
            continue;
        }
        for (file_name, text) in texts {
            output.push_str(&format!("{file_name}:\n\n```text\n"));
            output.push_str(text.trim_end());
            output.push_str("\n```\n\n");
        }
    }

    output.push_str("\n## Bundled assets\n");
    for path in BUNDLED_ASSET_NOTICES {
        let notice = fs::read_to_string(path)
            .map_err(|err| format!("failed to read bundled asset notice {path}: {err}"))?;
        output.push_str("\n```text\n");
        output.push_str(notice.trim_end());
        output.push_str("\n```\n");
    }

    fs::write(NOTICES_PATH, output)
        .map_err(|err| format!("failed to write {NOTICES_PATH}: {err}"))?;
    println!("Generated {NOTICES_PATH} ({} crates).", crates.len());
    Ok(())
}

// 出荷 target ごとの normal 依存 (build/dev 依存を除く) を union して (name, version) で返す
fn shipped_dependencies() -> Result<BTreeSet<(String, String)>, String> {
    let mut crates = BTreeSet::new();
    for target in SHIPPED_TARGETS {
        let stdout = run(
            "cargo",
            &[
                "tree",
                "--package",
                "coda",
                "--edges",
                "normal",
                "--prefix",
                "none",
                "--target",
                target,
            ],
            RunOptions {
                quiet: true,
                ..Default::default()
            },
        )?;
        for line in stdout.lines() {
            // 例: `serde v1.0.228`, `syntect v5.3.0 (*)`。`(/...)` は path 依存 = coda 自身
            if line.contains(" (/") {
                continue;
            }
            let mut parts = line.split_whitespace();
            let (Some(name), Some(version)) = (parts.next(), parts.next()) else {
                continue;
            };
            let Some(version) = version.strip_prefix('v') else {
                continue;
            };
            crates.insert((name.to_string(), version.to_string()));
        }
    }
    Ok(crates)
}

// `$CARGO_HOME/registry/src` 直下の index ディレクトリ一覧 (通常は 1 つ)
fn registry_src_dirs() -> Result<Vec<PathBuf>, String> {
    let cargo_home = env::var_os("CARGO_HOME").map(PathBuf::from).or_else(|| {
        env::var_os("HOME")
            .or_else(|| env::var_os("USERPROFILE"))
            .map(|home| PathBuf::from(home).join(".cargo"))
    });
    let src = cargo_home
        .ok_or("cannot locate cargo home (CARGO_HOME / HOME unset)")?
        .join("registry")
        .join("src");
    let entries = fs::read_dir(&src)
        .map_err(|err| format!("failed to read {}: {err}", src.display()))?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    Ok(entries)
}

fn find_crate_dir(registry_dirs: &[PathBuf], name: &str, version: &str) -> Option<PathBuf> {
    registry_dirs
        .iter()
        .map(|dir| dir.join(format!("{name}-{version}")))
        .find(|path| path.is_dir())
}

// crates.io に publish された crate の Cargo.toml は `license = "..."` を持つ。厳密な
// TOML parse はせず、xtask を無依存に保つため行頭一致で取り出す
fn license_expression(crate_dir: &Path) -> Option<String> {
    let manifest = fs::read_to_string(crate_dir.join("Cargo.toml")).ok()?;
    for line in manifest.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("license") {
            let rest = rest.trim_start();
            if let Some(value) = rest.strip_prefix('=') {
                return Some(value.trim().trim_matches('"').to_string());
            }
        }
    }
    None
}

// crate ルートのライセンス系ファイルを名前順に全部読む (NOTICE は Apache-2.0 §4(d) が
// 同梱を要求、COPYRIGHT は unicode 系 crate が使う)
fn license_texts(crate_dir: &Path) -> Result<Vec<(String, String)>, String> {
    let mut names: Vec<String> = fs::read_dir(crate_dir)
        .map_err(|err| format!("failed to read {}: {err}", crate_dir.display()))?
        .filter_map(|entry| entry.ok())
        .filter_map(|entry| entry.file_name().into_string().ok())
        .filter(|name| {
            let upper = name.to_ascii_uppercase();
            [
                "LICENSE",
                "LICENCE",
                "UNLICENSE",
                "COPYING",
                "COPYRIGHT",
                "NOTICE",
            ]
            .iter()
            .any(|prefix| upper.starts_with(prefix))
        })
        .collect();
    names.sort();

    names
        .into_iter()
        .map(|name| {
            let text = fs::read_to_string(crate_dir.join(&name))
                .map_err(|err| format!("failed to read {}/{name}: {err}", crate_dir.display()))?;
            // CRLF の LICENSE (bincode 等) をそのまま転記すると生成物が混在改行になり、
            // git の text=auto 正規化で毎回 warning が出るため LF に揃える
            Ok((name, text.replace("\r\n", "\n")))
        })
        .collect()
}
